spring:
  application:
    name: ajir


  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highLight_sql: true
        ddl-auto: validate

server:
  port: 80

logging:
  level:
    org:
    hibernate:
      orm:
        jdbc:
          bind: trace
      sql(debug):
        orm:
          jdbc:
            bind: trace